# Generated by Django 4.2.6 on 2023-10-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=3, unique=True)),
                ('batch_year', models.IntegerField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(max_length=10)),
                ('sub1', models.CharField(max_length=50)),
                ('sub2', models.CharField(max_length=50)),
                ('sub3', models.CharField(max_length=50)),
                ('sub4', models.CharField(max_length=50)),
                ('sub5', models.CharField(max_length=50)),
                ('sub6', models.CharField(max_length=50)),
                ('sub7', models.CharField(max_length=50)),
                ('sub8', models.CharField(max_length=50)),
                ('sub9', models.CharField(max_length=50)),
                ('sub10', models.CharField(max_length=50)),
                ('sub11', models.CharField(max_length=50)),
                ('sub12', models.CharField(max_length=50)),
                ('sub13', models.CharField(max_length=50)),
                ('sub14', models.CharField(max_length=50)),
                ('sub15', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherid', models.CharField(max_length=10)),
                ('t_name', models.CharField(max_length=50, unique=True)),
                ('t_dob', models.DateField()),
                ('t_mail', models.EmailField(max_length=254, unique=True)),
                ('t_phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=12, unique=True)),
                ('st_name', models.CharField(max_length=50, unique=True)),
                ('st_dob', models.DateField()),
                ('st_mail', models.EmailField(max_length=254, unique=True)),
                ('st_phone', models.IntegerField(max_length=10)),
                ('st_batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField(max_length=3)),
                ('s2', models.IntegerField(max_length=3)),
                ('s3', models.IntegerField(max_length=3)),
                ('s4', models.IntegerField(max_length=3)),
                ('s5', models.IntegerField(max_length=3)),
                ('s6', models.IntegerField(max_length=3)),
                ('s7', models.IntegerField(max_length=3)),
                ('s8', models.IntegerField(max_length=3)),
                ('s9', models.IntegerField(max_length=3)),
                ('s10', models.IntegerField(max_length=3)),
                ('s11', models.IntegerField(max_length=3)),
                ('s12', models.IntegerField(max_length=3)),
                ('s13', models.IntegerField(max_length=3)),
                ('s14', models.IntegerField(max_length=3)),
                ('s15', models.IntegerField(max_length=3)),
                ('sem_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.sem')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.student')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.teacher'),
        ),
    ]
