# Generated by Django 4.2.6 on 2023-10-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_batch_sem_teacher_student_mark_batch_batch_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_phone',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
