# Generated by Django 4.2.6 on 2023-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_st_name_alter_student_st_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='t_phone',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
