# Generated by Django 4.2.6 on 2023-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_teacher_t_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_phone',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
