# Generated by Django 4.2.6 on 2023-10-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_batch_batch_year_alter_student_st_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='count_subject',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='sem',
            name='count_of_sub',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.batch'),
        ),
    ]
