# Generated by Django 4.2.6 on 2023-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_mark_count_subject_sem_count_of_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='s1',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s10',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s11',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s12',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s13',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s14',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s15',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s2',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s3',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s4',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s5',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s6',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s7',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s8',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='mark',
            name='s9',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub1',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub10',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub11',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub12',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub13',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub14',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub15',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub2',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub3',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub4',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub5',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub6',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub7',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub8',
            field=models.CharField(default='no subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='sem',
            name='sub9',
            field=models.CharField(default='no subject', max_length=50),
        ),
    ]
